### PR TITLE
Improve styles

### PR DESCRIPTION
**Pull request by chapay**
- add Font Awesome icons
- set text color
- add dashed border

### CODE REVIEW

**Comment by sijad** [comment]
that's great :+1: thanks
but am not sure about using jQuery in `onclick` attribute, maybe it's better to handle changing the Font Awesome icon by css too?

**Comment by chapay** [comment]
As you wish, I can rewrite it.
But why not? I also try to avoid unnecessary dependencies, but JQuery is already included, so there is no overhead.

BTW: I think you can also fix #1 just using JQuery(but 2.1.4 supports only IE >= 9).

**Comment by sijad** [comment]
no need to rewrite, I'll take a look at it later
thanks again :smile:

**Comment by sijad** [comment]
@chapay I've submitted some changes and release new version, please let me know your username in flarum community to mention you in change log :smile: 
thanks again for your contribution

**Comment by chapay** [comment]
Great :+1:
It's the same as Github's – https://discuss.flarum.org/u/chapay
You are welcome!

**Pull request merged**
